name: Creating environment with env variables

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Enter the Repository name'
        required: true

      environment_name:
        description: 'Enter the environment name'
        required: true

      variable_name:
        description: 'Enter environment variable name'
        required: true

      variable_value:
        description: 'Enter value of environment variable'
        required: true
      

jobs:
  Create_environment_and_env_variable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install gh -y

    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.TOKEN }}" | gh auth login --with-token

    - name: Create Environment
      run: |
        repo="${{ github.event.inputs.repository }}"
        env_name="${{ github.event.inputs.environment_name }}"
        user=$(gh api user --jq '.login')

        gh api \
          -X PUT \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "/repos/${user}/${repo}/environments/${env_name}" \

    - name: Add Environment Variable
      run: |
        repo="${{ github.event.inputs.repository }}"
        env_name="${{ github.event.inputs.environment_name }}"
        var_name="${{ github.event.inputs.variable_name }}"
        var_value="${{ github.event.inputs.variable_value }}"

        gh api \
          -X PUT \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          //repos/${user}/${repo}/environments/${env_name}/variables/${var_name} \
          -f value="${var_value}"
