name: Add Environment Variable to Repositories

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment name'
        required: true
        default: 'Dev'
      variable_name:
        description: 'Environment variable name'
        required: true
        default: 'deploy_env'
      variable_value:
        description: 'Environment variable value'
        required: true

jobs:
  add-env-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          sudo apt-get install -y csvkit

      - name: Read and process CSV file
        id: read_csv
        run: |
          tail -n +2 github-workspace/repos.csv | csvcut -c 1 > repo_list.txt

      - name: Add Environment Variable to Repositories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENV_NAME: ${{ github.event.inputs.environment_name }}
          VAR_NAME: ${{ github.event.inputs.variable_name }}
          VAR_VALUE: ${{ github.event.inputs.variable_value }}
        run: |
          while IFS= read -r repo; do
            echo "Processing repository: $repo"
            echo "Fetching environments..."

            # Check if environment exists
            env_id=$(curl -sSf -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository_owner }}/$repo/environments | jq -r --arg ENV_NAME "$ENV_NAME" '.environments[] | select(.name == $ENV_NAME) | .id')

            if [ -z "$env_id" ]; then
              echo "Creating environment: $ENV_NAME"
              curl -sSf -X PUT -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository_owner }}/$repo/environments/$ENV_NAME
            else
              echo "Environment $ENV_NAME already exists"
            fi

            # Debug log to verify endpoint and payload
            echo "Adding environment variable: $VAR_NAME with value $VAR_VALUE to https://api.github.com/repos/${{ github.repository_owner }}/$repo/environments/$ENV_NAME/variables"
            
            # Add the environment variable
            response=$(curl -sSf -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository_owner }}/$repo/environments/$ENV_NAME/variables \
              -d "{\"name\":\"$VAR_NAME\", \"value\":\"$VAR_VALUE\"}")

            # Check response
            echo "Response: $response"
          done < repo_list.txt
