name: Sample App Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      parameter1:
        description: 'Enter parameter1 value'
        required: true
        default: 'default_value1'
        type: string
      parameter2:
        description: 'Enter parameter2 value'
        required: true
        default: 'default_value2'
        type: string

jobs:
  run-sample-app:
    runs-on: ubuntu-latest
    env:
      PARAM1: ${{ github.event.inputs.parameter1 }}
      PARAM2: ${{ github.event.inputs.parameter2 }}
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        echo "Running in environment: $ENVIRONMENT"
        echo "Parameter 1: $PARAM1"
        echo "Parameter 2: $PARAM2"

    - name: Run sample app
      run: |
        if [ "$ENVIRONMENT" == "dev" ]; then
          echo "Running in development environment"
          # Add commands for development environment
        elif [ "$ENVIRONMENT" == "test" ]; then
          echo "Running in test environment"
          # Add commands for test environment
        elif [ "$ENVIRONMENT" == "prod" ]; then
          echo "Running in production environment"
          # Add commands for production environment
        else
          echo "Unknown environment"
          exit 1
        fi
