name: Deploy NGINX & HTTPD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
      parameter1:
        description: 'DEV_ENV'
        required: true
        # default: 'default_value1'
        type: string
      parameter2:
        description: 'NGINX_CONF'
        required: true
        # default: 'default_value1'
        type: string
      parameter3:
        description: 'TEST_ENV'
        required: true
        # default: 'default_value1'
        type: string
      parameter4:
        description: 'HTTPD_CONF'
        required: true
        # default: 'default_value1'
        type: string

jobs:
  deploy-dev:
    if: ${{ github.event.inputs.environment == 'dev' }}
    runs-on: ubuntu-latest
    env:
      PARAM1: ${{ github.event.inputs.parameter1 }}
      PARAM2: ${{ github.event.inputs.parameter2 }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update and install NGINX
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx

    - name: Start NGINX
      run: |
        sudo systemctl start nginx
        sudo systemctl enable nginx

    - name: Verify NGINX is running
      run: |
        sudo systemctl status nginx

    - name: Copy NGINX configuration
      run: |
        sudo cp my-directory/$NGINX_CONF /etc/nginx/nginx.conf
        sudo systemctl restart nginx

  deploy-test:
    if: ${{ github.event.inputs.environment == 'test' }}
    runs-on: ubuntu-latest
    env:
      PARAM3: ${{ github.event.inputs.parameter3 }}
      PARAM4: ${{ github.event.inputs.parameter4 }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update and install httpd
      run: |
        sudo apt-get update
        sudo apt-get install -y httpd

    - name: Start NGINX
      run: |
        sudo systemctl start httpd
        sudo systemctl enable httpd

    - name: Verify NGINX is running
      run: |
        sudo systemctl status httpd

    - name: Copy NGINX configuration
      run: |
        sudo cp my-directory/$HTTPD_CONF /etc/httpd/httpd.conf
        sudo systemctl restart httpd

  deploy-prod:
    if: ${{ github.event.inputs.environment == 'prod' }}
    runs-on: ubuntu-latest
    env:
      APP_ENV: prod
      NGINX_CONF: prod/nginx.conf

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update and install NGINX
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx

    - name: Start NGINX
      run: |
        sudo systemctl start nginx
        sudo systemctl enable nginx

    - name: Verify NGINX is running
      run: |
        sudo systemctl status nginx

    - name: Copy NGINX configuration
      run: |
        sudo cp my-directory/$NGINX_CONF /etc/nginx/nginx.conf
        sudo systemctl restart nginx
