name: SA Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      param1:
        description: 'parameter1 value for dev environment'
        required: false
        type: string
      param2:
        description: 'parameter2 value for dev environment'
        required: false
        type: string
      param3:
        description: 'parameter3 value for test environment'
        required: false
        type: string
      param4:
        description: 'parameter4 value for test environment'
        required: false
        type: string

jobs:
  run-sample-app:
    runs-on: ubuntu-latest
    env:
      P1: ${{ github.event.inputs.param1 }}
      P2: ${{ github.event.inputs.param2 }}
      P3: ${{ github.event.inputs.param3 }}
      P4: ${{ github.event.inputs.param4 }}
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        echo "Running in environment: $ENVIRONMENT"
        if [ "$ENVIRONMENT" == "dev" ]; then
          echo "Parameter 1: $P1"
          echo "Parameter 2: $P2"
        elif [ "$ENVIRONMENT" == "test" ]; then
          echo "Parameter 3: $P3"
          echo "Parameter 4: $P4"
        fi

    - name: Run sample app
      run: |
        if [ "$ENVIRONMENT" == "dev" ]; then
          echo "Running in development environment"
          # Add commands for development environment
        elif [ "$ENVIRONMENT" == "test" ]; then
          echo "Running in test environment"
          # Add commands for test environment
        elif [ "$ENVIRONMENT" == "prod" ]; then
          echo "Running in production environment"
          # Add commands for production environment
        else
          echo "Unknown environment"
        fi
          
