name: List Repositories

on:
  workflow_dispatch:
    inputs:
      repos_list: ${{ steps.get_repos.outputs.repos }}

jobs:
  list_repos:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install GitHub CLI and jq
      run: |
        sudo apt-get update
        sudo apt-get install gh jq -y

    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.TOKEN }}" | gh auth login --with-token

    - name: List Repositories
      id: get_repos
      run: |
        org_name="srikanth-1612"
        repos=$(gh repo list $org_name --json name | jq -r '.[].name')
        echo "repositories=$(echo $repos | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Display Repositories
      run: |
        echo "Listed Repositories:"
        repos=$(echo "${{ env.repos }}" | tr ' ' '\n')
        echo "$repos"

    - name: List Environments
      id: get_envs
      run: |
        user="${{ github.event.inputs.owner }}"
        repo="${{ github.event.inputs.repository }}"
        environments=$(gh api --header "Authorization: token ${{ secrets.TOKEN }}" /repos/$user/$repo/environments | jq -r '.environments[].name')
        echo "environments=$environments" >> $GITHUB_ENV
